---
development:
  cloud_name: catstagram
  api_key: '139394879474972'
  api_secret: KLAhzCQU1XUY4O7Es9zTKe6j-DM
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: catstagram
  api_key: '139394879474972'
  api_secret: KLAhzCQU1XUY4O7Es9zTKe6j-DM
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: catstagram
  api_key: '139394879474972'
  api_secret: KLAhzCQU1XUY4O7Es9zTKe6j-DM
  enhance_image_tag: true
  static_image_support: false
