Comment.create!([
  {body: "I love the jewelry", user_id: 16, commentable_id: 2, commentable_type: "Medium"},
  {body: "So much dedication from ancient humans.", user_id: 16, commentable_id: 6, commentable_type: "Medium"},
  {body: "Your statues are amazing.", user_id: 16, commentable_id: 5, commentable_type: "Medium"},
  {body: "Love your family", user_id: 16, commentable_id: 50, commentable_type: "Medium"},
  {body: "A nice afternoon tan. I love those too.", user_id: 16, commentable_id: 49, commentable_type: "Medium"},
  {body: "Looks great!", user_id: 16, commentable_id: 40, commentable_type: "Medium"},
  {body: "Terrifyingly awesome", user_id: 16, commentable_id: 39, commentable_type: "Medium"},
  {body: "Will try this airlines next time.", user_id: 16, commentable_id: 52, commentable_type: "Medium"},
  {body: "I know! Cats were sacred.", user_id: 12, commentable_id: 2, commentable_type: "Comment"},
  {body: "Looking good.", user_id: 12, commentable_id: 85, commentable_type: "Medium"},
  {body: "The blanket looks comfy", user_id: 12, commentable_id: 82, commentable_type: "Medium"},
  {body: "Looks like fun.", user_id: 12, commentable_id: 49, commentable_type: "Medium"},
  {body: "Get some rest", user_id: 12, commentable_id: 48, commentable_type: "Medium"},
  {body: "Have fun.", user_id: 12, commentable_id: 40, commentable_type: "Medium"},
  {body: "You look good!", user_id: 12, commentable_id: 38, commentable_type: "Medium"},
  {body: "Happy Valentines!", user_id: 12, commentable_id: 42, commentable_type: "Medium"},
  {body: "Konichi wa", user_id: 12, commentable_id: 41, commentable_type: "Medium"},
  {body: "Great Photo", user_id: 13, commentable_id: 84, commentable_type: "Medium"},
  {body: "Nice sitting posture", user_id: 13, commentable_id: 2, commentable_type: "Medium"},
  {body: "Love the statue.", user_id: 13, commentable_id: 4, commentable_type: "Medium"},
  {body: "Great Painting", user_id: 13, commentable_id: 3, commentable_type: "Medium"},
  {body: "I have a friend that's a tiger too.", user_id: 13, commentable_id: 40, commentable_type: "Medium"},
  {body: "Great outfit.", user_id: 13, commentable_id: 43, commentable_type: "Medium"},
  {body: "Happy Valentines!", user_id: 13, commentable_id: 42, commentable_type: "Medium"},
  {body: "Hello too", user_id: 13, commentable_id: 41, commentable_type: "Medium"},
  {body: "I also like trees!", user_id: 15, commentable_id: 83, commentable_type: "Medium"},
  {body: "Ready for the hunt?!?", user_id: 15, commentable_id: 85, commentable_type: "Medium"},
  {body: "Great prowl pose.", user_id: 15, commentable_id: 84, commentable_type: "Medium"},
  {body: "Very regal", user_id: 15, commentable_id: 7, commentable_type: "Medium"},
  {body: "Cats are still sacred to some people. ", user_id: 15, commentable_id: 6, commentable_type: "Medium"},
  {body: "Your cubs are adorable.", user_id: 15, commentable_id: 50, commentable_type: "Medium"},
  {body: "Great rock.", user_id: 15, commentable_id: 51, commentable_type: "Medium"},
  {body: "I challenge you to a roaring contest.", user_id: 15, commentable_id: 48, commentable_type: "Medium"},
  {body: "Happy Valentines!", user_id: 15, commentable_id: 42, commentable_type: "Medium"},
  {body: "Rawr", user_id: 15, commentable_id: 41, commentable_type: "Medium"},
  {body: "You look great.", user_id: 18, commentable_id: 85, commentable_type: "Medium"},
  {body: "Nice shelter.", user_id: 18, commentable_id: 83, commentable_type: "Medium"},
  {body: "He looks content.", user_id: 18, commentable_id: 82, commentable_type: "Medium"},
  {body: "yeah", user_id: 18, commentable_id: 30, commentable_type: "Comment"},
  {body: "Great pose.", user_id: 18, commentable_id: 51, commentable_type: "Medium"},
  {body: "Love the patterns on the fur.", user_id: 18, commentable_id: 37, commentable_type: "Medium"},
  {body: "Staring back!", user_id: 18, commentable_id: 38, commentable_type: "Medium"},
  {body: "It's great.", user_id: 18, commentable_id: 8, commentable_type: "Comment"},
  {body: "Thank you.", user_id: 18, commentable_id: 23, commentable_type: "Comment"},
  {body: "Thanks", user_id: 18, commentable_id: 16, commentable_type: "Comment"},
  {body: "Thank you.", user_id: 18, commentable_id: 24, commentable_type: "Comment"},
  {body: "Domo Arigato", user_id: 18, commentable_id: 34, commentable_type: "Comment"},
  {body: "I'd eat you up.", user_id: 9, commentable_id: 26, commentable_type: "Medium"},
  {body: "Looks delicious.", user_id: 9, commentable_id: 33, commentable_type: "Medium"},
  {body: "Looks delicious.", user_id: 9, commentable_id: 31, commentable_type: "Medium"},
  {body: "Looks delicious.", user_id: 9, commentable_id: 30, commentable_type: "Medium"},
  {body: "Looks Tasty.", user_id: 9, commentable_id: 28, commentable_type: "Medium"},
  {body: "Cheer up.", user_id: 3, commentable_id: 27, commentable_type: "Medium"},
  {body: "Be happy.", user_id: 3, commentable_id: 25, commentable_type: "Medium"},
  {body: "Feel better.", user_id: 3, commentable_id: 24, commentable_type: "Medium"},
  {body: "You do look happier.", user_id: 3, commentable_id: 23, commentable_type: "Medium"},
  {body: "Chinese Cat Party", user_id: 3, commentable_id: 29, commentable_type: "Medium"},
  {body: "Be happy.", user_id: 3, commentable_id: 13, commentable_type: "Medium"},
  {body: "At least you look happy.", user_id: 3, commentable_id: 12, commentable_type: "Medium"},
  {body: "You look happy on your cushion.", user_id: 3, commentable_id: 11, commentable_type: "Medium"},
  {body: "Lose some weight you fat capitalist cat.", user_id: 5, commentable_id: 10, commentable_type: "Medium"},
  {body: "Stop eating everything you see.", user_id: 5, commentable_id: 9, commentable_type: "Medium"},
  {body: "Lose some weight you fat capitalist cat.", user_id: 5, commentable_id: 8, commentable_type: "Medium"},
  {body: "Lenin approves.", user_id: 5, commentable_id: 27, commentable_type: "Medium"},
  {body: "This is how everyone should look.", user_id: 5, commentable_id: 24, commentable_type: "Medium"},
  {body: "Too happy", user_id: 5, commentable_id: 35, commentable_type: "Medium"},
  {body: "No comment", user_id: 5, commentable_id: 32, commentable_type: "Medium"},
  {body: "No", user_id: 4, commentable_id: 53, commentable_type: "Comment"},
  {body: "No", user_id: 4, commentable_id: 48, commentable_type: "Comment"},
  {body: "No", user_id: 4, commentable_id: 54, commentable_type: "Comment"},
  {body: "No", user_id: 4, commentable_id: 55, commentable_type: "Comment"},
  {body: "NO", user_id: 4, commentable_id: 36, commentable_type: "Medium"},
  {body: "Too happy.", user_id: 4, commentable_id: 34, commentable_type: "Medium"},
  {body: "Nyan", user_id: 11, commentable_id: 89, commentable_type: "Medium"},
  {body: "Nyan", user_id: 11, commentable_id: 62, commentable_type: "Medium"},
  {body: "Nyan!", user_id: 11, commentable_id: 16, commentable_type: "Medium"},
  {body: "Nyan", user_id: 11, commentable_id: 75, commentable_type: "Medium"},
  {body: "Nyan!", user_id: 11, commentable_id: 94, commentable_type: "Medium"},
  {body: "Taste the rainbow.", user_id: 17, commentable_id: 78, commentable_type: "Medium"},
  {body: "Looks like he needs some cheetos.", user_id: 17, commentable_id: 64, commentable_type: "Medium"},
  {body: "Get him some Cheetos.", user_id: 17, commentable_id: 17, commentable_type: "Medium"},
  {body: "Can it eat cheetos?", user_id: 17, commentable_id: 76, commentable_type: "Medium"},
  {body: "Cheetos can grant magic powers.", user_id: 17, commentable_id: 90, commentable_type: "Medium"},
  {body: "What is this hippy doing on my ship?", user_id: 21, commentable_id: 81, commentable_type: "Medium"},
  {body: "Get off the poop deck.", user_id: 21, commentable_id: 88, commentable_type: "Medium"},
  {body: "I'd take a set for my next voyage.", user_id: 21, commentable_id: 15, commentable_type: "Medium"},
  {body: "Need one of these to man my ship.", user_id: 21, commentable_id: 77, commentable_type: "Medium"},
  {body: "I feel alone often as well.", user_id: 21, commentable_id: 92, commentable_type: "Medium"},
  {body: "Would look great as a sushi cat", user_id: 20, commentable_id: 80, commentable_type: "Medium"},
  {body: "Flaming sushi?", user_id: 20, commentable_id: 87, commentable_type: "Medium"},
  {body: "Stay away from my sushi.", user_id: 20, commentable_id: 61, commentable_type: "Medium"},
  {body: "Prowling for sushi?", user_id: 20, commentable_id: 91, commentable_type: "Medium"},
  {body: "I has a potion to stop addictions.", user_id: 19, commentable_id: 89, commentable_type: "Medium"},
  {body: "Need a spellcaster?", user_id: 19, commentable_id: 62, commentable_type: "Medium"},
  {body: "I love sushi", user_id: 19, commentable_id: 14, commentable_type: "Medium"},
  {body: "I saw a magic golem that's similar to this.", user_id: 19, commentable_id: 74, commentable_type: "Medium"},
  {body: "To the stars!", user_id: 14, commentable_id: 79, commentable_type: "Medium"},
  {body: "Robo Slam Dunk!", user_id: 14, commentable_id: 86, commentable_type: "Medium"},
  {body: "Need a robo bounty hunter?", user_id: 14, commentable_id: 60, commentable_type: "Medium"},
  {body: "RoboKitten always alone :(", user_id: 14, commentable_id: 88, commentable_type: "Comment"},
  {body: "Looking good.", user_id: 10, commentable_id: 47, commentable_type: "Medium"},
  {body: "Madness!", user_id: 10, commentable_id: 66, commentable_type: "Medium"},
  {body: "She looks great.", user_id: 10, commentable_id: 54, commentable_type: "Medium"},
  {body: "Love the fur.", user_id: 10, commentable_id: 59, commentable_type: "Medium"},
  {body: "Feed him!", user_id: 7, commentable_id: 71, commentable_type: "Medium"},
  {body: "Ok, fed him too much.", user_id: 7, commentable_id: 72, commentable_type: "Medium"},
  {body: "Call me!", user_id: 7, commentable_id: 69, commentable_type: "Medium"},
  {body: "Stay away, Spartan!", user_id: 7, commentable_id: 67, commentable_type: "Medium"},
  {body: "Grumpy Kratos?", user_id: 7, commentable_id: 65, commentable_type: "Medium"},
  {body: "Love the tail.", user_id: 7, commentable_id: 58, commentable_type: "Medium"},
  {body: "Looks amazing.", user_id: 7, commentable_id: 53, commentable_type: "Medium"},
  {body: "Pie!", user_id: 8, commentable_id: 73, commentable_type: "Medium"},
  {body: "I love the tanned fur!", user_id: 8, commentable_id: 46, commentable_type: "Medium"},
  {body: "I've been to the himalayas!", user_id: 8, commentable_id: 45, commentable_type: "Medium"},
  {body: "Poor burning temple.", user_id: 8, commentable_id: 68, commentable_type: "Medium"},
  {body: "I've always wanted to be a baker.", user_id: 6, commentable_id: 70, commentable_type: "Medium"},
  {body: "Madness?", user_id: 6, commentable_id: 44, commentable_type: "Medium"},
  {body: "Great carpet", user_id: 6, commentable_id: 57, commentable_type: "Medium"}
])
Like.create!([
  {medium_id: 1, user_id: 2},
  {medium_id: 2, user_id: 16},
  {medium_id: 6, user_id: 16},
  {medium_id: 5, user_id: 16},
  {medium_id: 50, user_id: 16},
  {medium_id: 49, user_id: 16},
  {medium_id: 40, user_id: 16},
  {medium_id: 39, user_id: 16},
  {medium_id: 52, user_id: 16},
  {medium_id: 85, user_id: 12},
  {medium_id: 82, user_id: 12},
  {medium_id: 50, user_id: 12},
  {medium_id: 49, user_id: 12},
  {medium_id: 40, user_id: 12},
  {medium_id: 38, user_id: 12},
  {medium_id: 42, user_id: 12},
  {medium_id: 84, user_id: 13},
  {medium_id: 2, user_id: 13},
  {medium_id: 4, user_id: 13},
  {medium_id: 3, user_id: 13},
  {medium_id: 40, user_id: 13},
  {medium_id: 43, user_id: 13},
  {medium_id: 42, user_id: 13},
  {medium_id: 41, user_id: 13},
  {medium_id: 83, user_id: 15},
  {medium_id: 85, user_id: 15},
  {medium_id: 84, user_id: 15},
  {medium_id: 7, user_id: 15},
  {medium_id: 50, user_id: 15},
  {medium_id: 51, user_id: 15},
  {medium_id: 48, user_id: 15},
  {medium_id: 41, user_id: 15},
  {medium_id: 42, user_id: 15},
  {medium_id: 85, user_id: 18},
  {medium_id: 83, user_id: 18},
  {medium_id: 82, user_id: 18},
  {medium_id: 6, user_id: 18},
  {medium_id: 50, user_id: 18},
  {medium_id: 51, user_id: 18},
  {medium_id: 49, user_id: 18},
  {medium_id: 37, user_id: 18},
  {medium_id: 38, user_id: 18},
  {medium_id: 26, user_id: 9},
  {medium_id: 33, user_id: 9},
  {medium_id: 31, user_id: 9},
  {medium_id: 30, user_id: 9},
  {medium_id: 28, user_id: 9},
  {medium_id: 24, user_id: 5},
  {medium_id: 89, user_id: 11},
  {medium_id: 62, user_id: 11},
  {medium_id: 16, user_id: 11},
  {medium_id: 75, user_id: 11},
  {medium_id: 94, user_id: 11},
  {medium_id: 64, user_id: 17},
  {medium_id: 17, user_id: 17},
  {medium_id: 76, user_id: 17},
  {medium_id: 90, user_id: 17},
  {medium_id: 88, user_id: 21},
  {medium_id: 15, user_id: 21},
  {medium_id: 77, user_id: 21},
  {medium_id: 92, user_id: 21},
  {medium_id: 87, user_id: 20},
  {medium_id: 91, user_id: 20},
  {medium_id: 74, user_id: 19},
  {medium_id: 79, user_id: 14},
  {medium_id: 86, user_id: 14},
  {medium_id: 60, user_id: 14},
  {medium_id: 47, user_id: 10},
  {medium_id: 66, user_id: 10},
  {medium_id: 71, user_id: 7},
  {medium_id: 72, user_id: 7},
  {medium_id: 69, user_id: 7},
  {medium_id: 67, user_id: 7},
  {medium_id: 65, user_id: 7},
  {medium_id: 58, user_id: 7},
  {medium_id: 53, user_id: 7},
  {medium_id: 45, user_id: 8},
  {medium_id: 68, user_id: 8},
  {medium_id: 70, user_id: 6},
  {medium_id: 44, user_id: 6},
  {medium_id: 57, user_id: 6}
])
Medium.create!([
  {title: "My Master and I", description: "", user_id: 19, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462161648/uqldyvzdabcleoplan1d.jpg"},
  {title: "I'm Alone", description: "", user_id: 19, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462161578/xgkc1ll7mosboi25iabt.jpg"},
  {title: "Prowling", description: "", user_id: 19, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462161547/yvi9up2jscnchxct7xz8.jpg"},
  {title: "Always Watching", description: "", user_id: 19, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462161517/wfnhmyxbot84q7xoxb9m.png"},
  {title: "The Addiction", description: "(From Family Guy)", user_id: 17, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462161401/i96n1rmob1zrt4w8vzvm.gif"},
  {title: "Cheetos!", description: "", user_id: 17, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462161360/rywwr0yiccv1jv8yflis.jpg"},
  {title: "Flaming Hot!", description: "Cheetos.", user_id: 17, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462161335/n0nph9ea1h8hb3ims8eh.jpg"},
  {title: "Slam Dunk", description: "", user_id: 17, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462161310/ninfdcvycrvohffu1dna.jpg"},
  {title: "Saw some prey.", description: "", user_id: 16, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462161156/pjl01zxywjhnbyxhidsj.jpg"},
  {title: "On the prowl", description: "", user_id: 16, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462158281/msoi9mtrb4azbzospkje.jpg"},
  {title: "We like trees.", description: "", user_id: 16, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462158141/hq5qbg1uigctpp3fksqe.jpg"},
  {title: "My friend at the zoo", description: "", user_id: 16, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462158111/i9nsvka86jrbanyujj4m.jpg"},
  {title: "Hippy Nyan", description: "", user_id: 11, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462156378/tz8zbw3dhdh9ub346ijg.gif"},
  {title: "2.5D Nyan", description: "", user_id: 11, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462156345/l0fzeejmplsmoynik3f7.jpg"},
  {title: "Nyan!!", description: "", user_id: 11, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462156313/qd4inynz7nrtvva8nwsf.jpg"},
  {title: "Nyan", description: "", user_id: 11, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462156295/fyqsh4vheelsgi8eqvbu.jpg"},
  {title: "Meowingtons rev2.5", description: "", user_id: 14, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462154189/ubjs3ldfl1pm2ehsuggg.jpg"},
  {title: "Meow Bow Wow", description: "", user_id: 14, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462153977/mgbq36gl4co95we9zztd.jpg"},
  {title: "Mechanized Hunter", description: "Ready to hunt!", user_id: 14, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462153793/k31hmgdahrlrmfwdk6ux.jpg"},
  {title: "Patience", description: "", user_id: 14, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462153745/aysijgtp3cctbc3kdr0h.jpg"},
  {title: "Pie!", description: "", user_id: 10, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462151977/dgie1mt1isgp6mlxhcv8.gif"},
  {title: "Overate", description: "", user_id: 10, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462151957/hr3z73qsgsleiqomb5k3.gif"},
  {title: "Hungry", description: "", user_id: 10, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462151935/zdyku3uuuyeeu8jh6jus.jpg"},
  {title: "Cup Cake!", description: "", user_id: 10, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462151911/x2y7kgnmfgiuiujjxzmy.jpg"},
  {title: "Phone Time!", description: "", user_id: 10, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462151881/xmnnyphe9g54drzw7xwg.gif"},
  {title: "They will pay", description: "", user_id: 6, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462151634/efnzaxvntbadrcbj6opr.jpg"},
  {title: "King Catnidas", description: "", user_id: 6, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462151590/tsi0we7dtujgvseamnkt.jpg"},
  {title: "Nothing else need be said", description: "", user_id: 6, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462151520/ckeqmjtsj9vfm1hfnimi.jpg"},
  {title: "The new convert", description: "", user_id: 6, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462151409/bdnt5gtongiodeet2azx.jpg"},
  {title: "My Navigator", description: "Trying to work the controls.", user_id: 21, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462150801/pbhqjxi56avotvrzyeol.jpg"},
  {title: "First mate", description: "", user_id: 21, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462150694/lxcxxrbaeywko1cooyot.jpg"},
  {title: "Meet this one off of Haiti", description: "", user_id: 21, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462150636/lmodmkwl8j1kdujd2qi0.jpg"},
  {title: "My Nemesis", description: "", user_id: 21, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462150606/pz35sblzzqe8dhdxbl7j.jpg"},
  {title: "Sister", description: "", user_id: 8, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462148002/zvagwgt7gfcroakwuank.jpg"},
  {title: "So jealous of her tail", description: "", user_id: 8, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462147969/qoe5slfmimixwrroe7uy.jpg"},
  {title: "Favorite Rug", description: "", user_id: 8, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462147949/yad0cfgogmzlr0gemjsw.jpg"},
  {title: "Mom", description: "", user_id: 8, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462147770/hmrteatpjnwclsnr6t0l.jpg"},
  {title: "Cousin", description: "", user_id: 8, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462147740/auzm1er7tgdg2upexy4j.jpg"},
  {title: "Kitty Airlines", description: "", user_id: 18, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462147471/vrjobarkkorzdqcsed1l.png"},
  {title: "My rock", description: "Found a new rock to rest on.", user_id: 13, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462147087/ojxvcmplua00q57w9dmd.jpg"},
  {title: "My Boys", description: "Aren't they adorable?", user_id: 13, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462147000/mvbi2qegjssdaipqzmmy.jpg"},
  {title: "Chilling", description: "Nothing like a tan after a meal.", user_id: 13, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462146946/hnxt2c1ydtd3semdwnac.jpg"},
  {title: "Just Yawning", description: "DIdn't sleep well last night.", user_id: 13, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462146074/y2x9gwvwsabjopveliu3.jpg"},
  {title: "Come play with me", description: "", user_id: 7, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462145230/oqk4mz6iixbgsrfvr0z7.jpg"},
  {title: "He tanned his fur!", description: "", user_id: 7, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462144663/ykka2jm5g1elntrxct32.jpg"},
  {title: "Himalayan Cousin", description: "", user_id: 7, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462144632/mppwv7eziqtfoa8q3j1o.jpg"},
  {title: "Selfie?", description: "", user_id: 7, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462144070/oemqi4uh0itmgrb6qdvv.jpg"},
  {title: "I love to dance!", description: "", user_id: 18, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462136625/epo9ceyywhjjiyfvngeq.gif"},
  {title: "Hello there", description: "", user_id: 18, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462136121/vtygnzuotx7efzwz00wg.jpg"},
  {title: "Hi", description: "", user_id: 18, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462136095/flbgvi0sgygn6li8eouz.jpg"},
  {title: "White Tiger Friend", description: "We finally meet again.", user_id: 15, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462134010/x77n4urdeeg9kdocba9n.jpg"},
  {title: "Back off", description: "Check out my awesome teeth.", user_id: 15, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462133636/ecy5fxqg3nv4u5xzn7ee.jpg"},
  {title: "Staring at you!", description: "Come over here.", user_id: 15, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462133359/yfabrvlyok5fbtzvvf6g.jpg"},
  {title: "Bengal Tiger", description: "", user_id: 15, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462133291/iyjgsj4nu0kowijvsgyn.jpg"},
  {title: "YES", description: "", user_id: 3, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462133034/nlhmtaozywhgwxge5mic.jpg"},
  {title: "Surprise!", description: "", user_id: 3, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462132950/u3vdltpnvxwiqcdjyijb.jpg"},
  {title: "=D", description: "", user_id: 3, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462132929/xn3da1meqcoewznvsguo.jpg"},
  {title: "mmmmMMMM?!?", description: "", user_id: 3, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462132904/mdlfloyasa1yqlrmi9mc.jpg"},
  {title: "Happy!", description: "", user_id: 3, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462132873/ifgw9ourpgrkayc1w0wa.jpg"},
  {title: "Official from the Kremlin", description: "", user_id: 5, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462132682/xot5sj1rmnwub76dv9vg.png"},
  {title: "Approval from Lenin", description: "", user_id: 5, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462132607/zk8bug5qu9kjmjd1iakr.jpg"},
  {title: "Don't be a pussy.", description: "", user_id: 5, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462132545/lkodv3pvv3osnu6z0lej.png"},
  {title: "Hail Great Leader", description: "", user_id: 5, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462132502/pmtywhzivyiinytrropq.gif"},
  {title: "Can I go now?", description: "", user_id: 4, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462009015/g1o8uzzpb8xi6qxfgsem.jpg"},
  {title: "I'm not amused.", description: "", user_id: 4, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462008982/aaiy2lumbomopxmue9rq.png"},
  {title: "Nope", description: "", user_id: 4, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462008964/up7tt5uvptkju4gw07qb.jpg"},
  {title: "... ... !!", description: "", user_id: 4, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462008939/yprpltcnubfj9dypfxth.jpg"},
  {title: "On a good day", description: "", user_id: 4, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462008881/sj5j4qglqpbwsljam0vc.jpg"},
  {title: "Js!", description: "", user_id: 2, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462008798/rlocyi86o3gg19fnq6dq.png"},
  {title: "Heroku!", description: "", user_id: 2, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462008771/ocqzrjwgcqztfivaazdu.png"},
  {title: "Rails!!", description: "", user_id: 2, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462008745/tzvvakfgpdjwsuhnlhtj.jpg"},
  {title: "React!", description: "", user_id: 2, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462008722/hjlwh95nf3zzqyjt05kt.png"},
  {title: "a/A", description: "", user_id: 2, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462008679/nhbvn1tkazt7eteytdrr.png"},
  {title: "DaVinci sushi", description: "", user_id: 20, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462008617/kwwerq45pxgviovusb5h.jpg"},
  {title: "Tasty fish", description: "Sooo hungry.", user_id: 20, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462006714/ptg7rjtfkqoa6syg1ucd.jpg"},
  {title: "Sushi cat sushi set!", description: "All you can nom.", user_id: 20, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462006681/wnop5enxfreqilxtylnd.jpg"},
  {title: "Black Sushi Cat!", description: "", user_id: 20, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462006651/v1z5xxbbggpnwgc4azu3.png"},
  {title: "Stop dragging me.", description: "Let me lie in peace.", user_id: 9, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462006053/gwcpifdfdzpdxxpl1pcd.jpg"},
  {title: "Halp!", description: "I can't get down.", user_id: 9, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462005899/kzwe8cvcnhqux0zdlgfo.jpg"},
  {title: "Why exercise", description: "When you have a pillow.", user_id: 9, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462005838/gcqa3xvi9wd5bueamxlr.jpg"},
  {title: "My cousin", description: "", user_id: 9, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462005802/vkybg2nwufhhkxqjkn7v.jpg"},
  {title: "Dinner?", description: "", user_id: 9, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462005770/wlkzmcxa1z22bb487ght.jpg"},
  {title: "Getting too big for this.", description: "Someone help me move.", user_id: 9, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462005655/caymdj8x5yrz2axvffae.jpg"},
  {title: "Egyptian Cat Art", description: "", user_id: 12, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462005580/zdnorcwpbvrgfm7y71f7.jpg"},
  {title: "CatGlyph", description: "Ancient cat carving.", user_id: 12, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462005425/j8265xihhtivezhrmlnl.jpg"},
  {title: "Egyptian Cat Statues", description: "set and bast", user_id: 12, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462005358/aponqbaqbflx4xq8kazi.jpg"},
  {title: "Bast Cat", description: "Bast!", user_id: 12, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462005159/j0alehosfy44o2mav0cd.jpg"},
  {title: "Egyptian Black Cat", description: "", user_id: 12, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462005110/po2msynziazssewbztph.jpg"},
  {title: "Egyptian Cat", description: "A bit stretched", user_id: 12, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1461974415/cpq0101ur1k1kiib3unl.jpg"},
  {title: "Sample Image", description: "This is a sample.", user_id: 1, media_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1461969900/e024p9ugr8h7ewj7kdby.jpg"}
])
Relationship.create!([
  {follower_id: 2, following_id: 1},
  {follower_id: 20, following_id: 2},
  {follower_id: 1, following_id: 11},
  {follower_id: 1, following_id: 15},
  {follower_id: 1, following_id: 9},
  {follower_id: 1, following_id: 2},
  {follower_id: 16, following_id: 12},
  {follower_id: 16, following_id: 13},
  {follower_id: 16, following_id: 15},
  {follower_id: 12, following_id: 16},
  {follower_id: 12, following_id: 13},
  {follower_id: 12, following_id: 15},
  {follower_id: 13, following_id: 16},
  {follower_id: 13, following_id: 12},
  {follower_id: 13, following_id: 15},
  {follower_id: 18, following_id: 13},
  {follower_id: 18, following_id: 15},
  {follower_id: 18, following_id: 12},
  {follower_id: 18, following_id: 16},
  {follower_id: 15, following_id: 12},
  {follower_id: 15, following_id: 16},
  {follower_id: 15, following_id: 13},
  {follower_id: 15, following_id: 18},
  {follower_id: 9, following_id: 4},
  {follower_id: 3, following_id: 4},
  {follower_id: 3, following_id: 5},
  {follower_id: 3, following_id: 9},
  {follower_id: 9, following_id: 5},
  {follower_id: 9, following_id: 3},
  {follower_id: 5, following_id: 9},
  {follower_id: 5, following_id: 4},
  {follower_id: 5, following_id: 3},
  {follower_id: 11, following_id: 17},
  {follower_id: 11, following_id: 21},
  {follower_id: 11, following_id: 20},
  {follower_id: 11, following_id: 14},
  {follower_id: 11, following_id: 19},
  {follower_id: 17, following_id: 11},
  {follower_id: 17, following_id: 20},
  {follower_id: 17, following_id: 21},
  {follower_id: 17, following_id: 14},
  {follower_id: 17, following_id: 19},
  {follower_id: 21, following_id: 11},
  {follower_id: 21, following_id: 17},
  {follower_id: 21, following_id: 20},
  {follower_id: 21, following_id: 14},
  {follower_id: 21, following_id: 19},
  {follower_id: 20, following_id: 11},
  {follower_id: 20, following_id: 17},
  {follower_id: 20, following_id: 21},
  {follower_id: 20, following_id: 19},
  {follower_id: 20, following_id: 14},
  {follower_id: 19, following_id: 17},
  {follower_id: 19, following_id: 21},
  {follower_id: 19, following_id: 20},
  {follower_id: 19, following_id: 14},
  {follower_id: 14, following_id: 11},
  {follower_id: 14, following_id: 17},
  {follower_id: 14, following_id: 21},
  {follower_id: 14, following_id: 20},
  {follower_id: 14, following_id: 19},
  {follower_id: 10, following_id: 7},
  {follower_id: 10, following_id: 6},
  {follower_id: 10, following_id: 8},
  {follower_id: 7, following_id: 10},
  {follower_id: 7, following_id: 6},
  {follower_id: 7, following_id: 8},
  {follower_id: 8, following_id: 7},
  {follower_id: 8, following_id: 6},
  {follower_id: 6, following_id: 7},
  {follower_id: 6, following_id: 8}
])
User.create!([
  {username: "bast", displayname: "Bast", password_digest: "$2a$10$7Ae0MTeurIR86e1jaTSkTOUlWWVoRJE8yVR/vqiQkGHn6/Yy7/LJ6", session_token: "K9x0e9_8msudYLDRwcq_YQ", profile_pic_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1461974376/z6lfwufdgwl2z4p7vj9h.jpg", description: "Egyptian Goddess of Cats"},
  {username: "chairman meow", displayname: "Chairman Meow", password_digest: "$2a$10$Nul/fqj8l0A2AQ2WklpOCux5H/pFjcSXcDZnGGrn31lc9e3IBF0rW", session_token: "EsYHejec6ha2TDIrsnQzBQ", profile_pic_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462132440/jrrccub8htllzhep5fif.jpg", description: "Great Leader!"},
  {username: "chester", displayname: "Chester", password_digest: "$2a$10$Rw3gn/zQcU3gyIJjkbJn/.g3nCbOXlYyD/t.sPRMO0OXCRshnSh2q", session_token: "IUhw-HQJ9C26DIL0yuCJjw", profile_pic_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462161255/zvq9qebbsrw5sijqzx5a.jpg", description: "Cheetos"},
  {username: "cpt. cat", displayname: "Cpt. Cat", password_digest: "$2a$10$b7uas2/eix.fIv4F7m3DdO/Og/ZWaxZTcMFp9eUjjQq2.W93iCDIC", session_token: "KgyzQyDdqPc8Bud21o1UVA", profile_pic_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462150550/g9hm1hqxpk6q7tit6op2.jpg", description: "All hands on deck!"},
  {username: "crookshanks", displayname: "Crookshanks", password_digest: "$2a$10$.g/U1tGcdg2HG3igsjszyu6eYI5BXrxQZi9i4JHP2DdnIIbEVbXDu", session_token: "DYk2Q8zoJMLaYtfXXyky1w", profile_pic_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462161472/m58d14zpvq1dwa6q4nap.gif", description: "I can has magic"},
  {username: "fat cat", displayname: "Fat Cat", password_digest: "$2a$10$lbtC5166QvjU/iqT4yKtQ.AaqO48jHEDCbzukuGctOFDBqN/vaX2C", session_token: "sKaw0aGEyBfSCl9IUjgU7w", profile_pic_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462005708/gebb2ukikmwmzjp8chsi.jpg", description: "Nom Nom Nom."},
  {username: "grumpy cat", displayname: "Grumpy Cat", password_digest: "$2a$10$iOBOj6GSUnl9r3/FBpG5e.YFuxIe1EM2a/vtsWC0w6MqaD9kU/a1.", session_token: "RN80SBhtGfynV4pJE_HbqA", profile_pic_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462008919/t4fzncmkmaud5kxclzmj.jpg", description: "mmm No."},
  {username: "guest", displayname: "Guest", password_digest: "$2a$10$1T3CqrEyvKL.M80cTtTF5.6mZvuiTcRD0Y/PPTB1xxtkWqTb0X22u", session_token: "ZvQLEKeCed_YELD3ZQTGbg", profile_pic_url: "http://res.cloudinary.com/catstagram/image/upload/v1445632575/Anonymous_denjpa.png", description: "Welcome to the guest account!"},
  {username: "happycat", displayname: "HappyCat", password_digest: "$2a$10$PnhI7DgmOklSIjGMcz6LXucJ1OvvlrTlhJz65N28L5WedYnQd79R.", session_token: "vA5_34YjPndWlqm1uavbNg", profile_pic_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462132855/fxk6qm9imeprcjn2t21j.jpg", description: "Such Happiness!"},
  {username: "hello kitty", displayname: "Hello Kitty", password_digest: "$2a$10$jkJHyohzV5eYXXSVOpvCDeeZFHH7CZnbQQai2OJdfK/f0Zir0HFN6", session_token: "Ebm9uPoYTmaur0ukKSTC5g", profile_pic_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462135708/xdg49czzl7kvtl2lijbq.jpg", description: "Hello"},
  {username: "lioness", displayname: "Lioness", password_digest: "$2a$10$pgJVOEhE4lLM2iD8aapkCOajWM0O10XKoTyko3NojM1ubqnfDydU.", session_token: "dBJP6wsjiD0u3HGqgdllUA", profile_pic_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462145334/xie4a5dwxmrvyjnduzxz.jpg", description: "Stay away from my cubs."},
  {username: "nyan cat", displayname: "Nyan Cat", password_digest: "$2a$10$iXSffBzNNhzpJwWtqzapXOes/VtG/QCQapDhEIuwaWtlv6Qm3q.ty", session_token: "OO8pfpeDTOoWhCSMgEPhJw", profile_pic_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462156274/qkhcqd9khavtknxzuff6.gif", description: "Nyan Nyan"},
  {username: "ocelot", displayname: "Ocelot", password_digest: "$2a$10$jpeAUQMTRk9fHPS7xEybi.Y7YuKXdHR7eJKvDda/A75XzV0L0gura", session_token: "80Wtl7tly4hCe4FM9iQW0Q", profile_pic_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462157781/rz7z2uouamhxwei2u2cp.jpg", description: "I'm an ocelot."},
  {username: "persian persian", displayname: "Persian Persian", password_digest: "$2a$10$2RejC6irOkfcjEFCOpdM4uLN/W0pvZX7KA05mE1s2.sl0zazM1rZG", session_token: "aUoUR_sQL0oa5y3j_fez1Q", profile_pic_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462143935/bgzriiz6is8lyowji8ka.jpg", description: "I'm a Persian"},
  {username: "pusheen", displayname: "Pusheen", password_digest: "$2a$10$YAew2xcS0PVoWnTUnGiCveZaXAe4w5aZpAvteEmaW7W/UanD7E00i", session_token: "8-ooDVc6sXLh0Q7wPc2iCw", profile_pic_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462151711/yjbsnot4bivx6p46e2pt.png", description: "Meow! I'm Pusheen."},
  {username: "robokitten", displayname: "RoboKitten", password_digest: "$2a$10$BhM7km5jN/ICw/zUtb7SMOVQZS5vv/GJZvrtyB7Pcp2MPcPtXtXNy", session_token: "49t7wsIsuu4yF5jCYaiF4w", profile_pic_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462152805/n2f5crpxxvaqfvnbijrj.jpg", description: " M E O W"},
  {username: "sheng da zhang", displayname: "Sheng Da Zhang", password_digest: "$2a$10$tz.48HIswKnQ.PvET2hbAe85TCCr4WtU5IA3SWaR/O.qJ8FzRqGAK", session_token: "7fMWE1KY1Uw8WDSFHdpraQ", profile_pic_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1461971331/unxyifnc65ra8kopavpe.jpg", description: "Master Account"},
  {username: "siamese only", displayname: "Siamese Only", password_digest: "$2a$10$3PkTWBCgBn297r4QuqyFcukxPJzNg.B5HSVPI5qTWVAlTVFup0OTy", session_token: "ucTlhpsTJ0bncithBTu_UA", profile_pic_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462147688/iwpnujrx3lup18ecwgj8.jpg", description: "All the way from Siam"},
  {username: "spartan kitten", displayname: "Spartan Kitten", password_digest: "$2a$10$fN0xFIflePDXvQ7vBZ32geiAdVDQm2VyAxNn4EWpXlgYRFY/bUDky", session_token: "tq9BEZgKSSsRQEq5mZMpXw", profile_pic_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462151328/ykkgoblid4cvwhwmisso.jpg", description: "This is Sparta!!"},
  {username: "sushi cat", displayname: "Sushi Cat", password_digest: "$2a$10$fQ8EkvZHKCY3z1chvyeCzujnY1aKzsvCSzI3rrCf8PuXekp1pOoVe", session_token: "VU_I9rjf_BAASwSq9i9LAg", profile_pic_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462006119/ggosvekurxqszj9f60qf.png", description: "Don't eat me!"},
  {username: "tora", displayname: "Tora", password_digest: "$2a$10$q3bsOVEWpKUDDeOiIFitnOvD4QvTZpdvQQH0BThLsQzZhQES0PEYG", session_token: "xfSHzr0XqPOjlw2Cvw5lvQ", profile_pic_url: "https://res.cloudinary.com/catstagram/image/upload/h_600,w_600/v1462133255/sltcr9zxw4cyiilcgfwm.jpg", description: "Rawr"}
])
